version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
